version: 1.{build}
pull_requests:
  do_not_increment_build_number: true
os: Visual Studio 2013
configuration: Release
platform:
- Win32
before_build:
  - dir /s *.exe
build:
  project: miniweb_vc11.sln
  parallel: true
  verbosity: minimal
